import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";

import { Michroma, Geist, Geist_Mono } from "next/font/google";
import { Kanit } from 'next/font/google';

const kanit = Kanit({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // Add any weights you need
  variable: '--font-kanit',
  display: 'swap',
});


const michroma = Michroma({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-michroma",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Online Bank",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${michroma.variable} ${geistSans.variable} ${geistMono.variable} ${kanit.variable}`}
    >
      <head>
        <link rel="icon" href="/tablogo.png" type="image/png" />
        {/* ✅ Import Bitcount Grid Double manually from Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Bitcount+Grid+Double&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
